spring:
  main:
    banner-mode: "off"
  application:
    name: s1pdgs-s3-pug-ipf-execution-worker
    
logging:
  config: ${log4j_config:log/log4j2.yml}
    
# REST controller
server:
  port: 8080                              # port used for publishing REST API around wrapper status

# KAFKA config for error queue
kafka:
  bootstrap-servers: ${kafka_bootstrap-servers:kafka-headless:9092}   # the bootstrap servers for KAFKA
  group-id: error                                                # the group identifier to use for KAFKA publishers  
  max-retries: 10                                                # number of retries if kafka is not available
  error-topic: t-pdgs-errors  

metadata:
  host: ${catalog_rest_host} 
  rest-api_nb-retry: 3  
  rest-api_tempo-retry-ms: 3000 
    
process:
  level: S3_PDU                              # application level (L0/L1)
  hostname: ${HOSTNAME}                   # Hostname
  workingDir: /data/localWD 
  fixed-delay-ms: 500                     # (fixed delay) period in milliseconds between 2 polls of next message
  init-delay-poll-ms: 1000                # the initial delay to apply before consuming messages
  tm-proc-one-task-s: 600                 # Timeout in second for stopping task of pool's task execution
  tm-proc-all-tasks-s: 1800               # Timeout in second for stopping task of pool execution
  tm-proc-stop-s: 300                     # Timeout in second for stopping task of pool execution
  tm-proc-check-stop-s: 60                # Timeout in second for stopping the task of waiting for required inputs before starting processing
  size-batch-upload:  10            # !!!!! the size of the batch used for uploading outputs
  size-batch-download: 10           # !!!!! the size of the batch used for downloading inputs
  wap-nb-max-loop: 12                     # the maximal number of loop when waiting for required inputs before starting processing
  wap-tempo-s: 1                          # the temporisation (in second) applied between 2 loops when waiting for required inputs before starting processing
  threshold-ew : 2                        # ghost threshold ES
  threshold-iw : 2                        # ghost threshold IW
  threshold-sm : 2                        # ghost threshold SM
  threshold-wv : 30                       # ghost threshold WV
  path-job-order-xslt: /app/config/jobOrder.xslt # xslt to transform jobOrder for ipf
  
mqi:
  host-uri: http://localhost:8081       # the host and port for querying MQI server
  max-retries: 45                        # the maximal number of consecutive retries following a MQI request error 
  tempo-retry-ms: 2000                  #

status:
  delete-fixed-delay-ms: 3000             # (fixed delay) period in milliseconds between 2 check if application shall be stopped or not
  max-error-counter-processing: 3         # the number of consecutive processing errors leading to the state FATALERROR
  max-error-counter-mqi: 30               # the number of consecutive MQI errors leading to the state FATALERROR

dev:
  steps-activation:
    download: true                        # if false, the wrapper ignores the step around input downloading
    upload: true                          # if false, the wrapper ignores the step around outputs processing
    erasing: false                         # if false, the wrapper ignores the step around working directory cleaning