spring:
  main:
    banner-mode: "off"
  application:
    name: s3-l0-production-trigger
    
# Logging
logging:
  config: ${log4j_config:log/log4j2.yml}
  
mqi:
  host-uri: http://localhost:8081                               # the host and port for querying MQI server
  max-retries: 45                                                # the maximal number of consecutive retries following a MQI request error 
  tempo-retry-ms: 2000
 
metadata:
  host: ${catalog_rest_host} 
  rest-api_nb-retry: 100  
  rest-api_tempo-retry-ms: 3000 

# Kafka config
kafka:
  # host:port to use for establishing the initial connection to the Kafka cluster
  bootstrap-servers: ${kafka_bootstrap-servers}
  # Hostname
  hostname: ${HOSTNAME}
  # Topic name for the errors
  error-topic: t-pdgs-errors
  # Kafka Producer config
  producer:
    # When greater than zero, enables retrying of failed sends
    max-retries: 10

appcatalog:
  host-uri: http://s1pro-app-catalog-svc:8080                    # URI of the applicative data catalog APIs -DMA-
  max-retries: 3                                                 # Nb Max of retry to connect API 
  tempo-retry-ms: 1000                                           # Tempo before a retry to connect API  
  tm-connect-ms: 5000                                            # Timeout of connections to the API  

status:
  delete-fixed-delay-ms: 1800000                                   # (fixed delay) period in milliseconds between 2 check if application shall be stopped or not
  max-error-counter-processing: 3                                  # the number of consecutive processing errors leading to the state FATALERROR
  max-error-counter-mqi: 30                                        # the number of consecutive MQI errors leading to the state FATALERROR
  
tasktable:
  pathroutingxmlfile: /app/config/routing.xml                      # Location of the routing file
  routingKeyTemplate: $(product.productType)_$(product.satelliteId)

process:
  level: S3_L0                                                        # Level for job generator 
  product-type: S3_L0_Granule
  hostname: ${HOSTNAME}                                            # Hostname 
  fixed-delay-ms: 200                                              # (Fixed delay) Dealy in milliseconds between 2 next messages
  initial-delay-ms: 5000                                           # Initial delay in missliseconds before the first next message
  category: s3-products

