spring:
  main:
    banner-mode: "off"
  application:
    name: s1pdgs-s3-acq-production-trigger
    
# Logging
logging:
  config: ${log4j_config:log/log4j2.yml}
  
mqi:
  # The host and port for querying MQI server
  host-uri: http://localhost:8081
  # The maximal number of consecutive retries following a MQI request error, default is 3
  max-retries: 45
  # Time between retries in milliseconds, default is 1000
  tempo-retry-ms: 2000
  
metadata:
  # Metadata Catalog host
  host: ${catalog_rest_host}
  # Maximal number of retries when query fails
  rest-api_nb-retry: {{ .Values.metadataCatalog.restApiNbRetry }}
  # Temporisation in ms between 2 retries
  rest-api_tempo-retry-ms: {{ .Values.metadataCatalog.restApiTempoRetryMs }} 

# Kafka config
kafka:
  # host:port to use for establishing the initial connection to the Kafka cluster
  bootstrap-servers: ${kafka_bootstrap-servers}
  # Hostname
  hostname: ${HOSTNAME}
  # Topic name for the errors
  error-topic: ${kafka_topic_errors}
  # Kafka Producer config
  producer:
    # When greater than zero, enables retrying of failed sends
    max-retries: 10

# Applicative Catalog config
appcatalog:
  # URI of the applicative data catalog APIs
  host-uri: http://s1pro-app-catalog-svc:8080
  # Number of max retries to connect API
  max-retries: 3
  # TempoRetry rate for retries to connect API
  tempo-retry-ms: 1000
  # Timeout of connections to the API
  tm-connect-ms: 5000

# Application status configuration
status:
  # (fixed delay) period in milliseconds between 2 check if application shall be stopped or not, default is 3000
  delete-fixed-delay-ms: 1800000
  # The number of consecutive processing errors leading to the state FATALERROR, default is 100
  max-error-counter-processing: 3
  # The number of consecutive MQI errors leading to the state FATALERROR, default is 100
  max-error-counter-mqi: 30

tasktable:
  # Filename of the tasktable to use
  name: TaskTable.AIOP.xml

process:
  # Level for job generator, possible values: L0, L0_SEGMENT, L1, L2, SPP_MBU, SPP_OBS, S3_L0, S3_L1, S3_L2, S3_PDU
  level: L0
  # Product type to process, only for logging/reporting purposes
  product-type: EdrsSession
  # Hostname
  hostname: ${HOSTNAME}
  # (Fixed delay) Delay in milliseconds between 2 next messages
  fixed-delay-ms: 200
  # Initial delay in missliseconds before the first next message
  initial-delay-ms: 5000
  # Product category to process, possible values: edrs-sessions, level-segments, level-products, spp-products
  category: edrs-sessions

