Configuration:
  status: warn
  name: YAMLConfigTest
  thresholdFilter:
    level: debug
  appenders:
    Console:
      - name: STDOUT
        PatternLayout:
          Pattern: "{\"header\":{\"type\":\"LOG\",\"timestamp\":\"%d{yyyy-MM-dd'T'HH:mm:ss.nnnnnn}Z\",\"level\":\"%level\",\"line\":%L,\"file\":\"%.255F\",\"thread\":\"%.255t\"},\"message\":{\"content\":\"%enc{%m%xEx}{JSON}\"},\"custom\":{\"logger_string\":\"%logger\"}}%n"    
      - name: REPORT
        PatternLayout:
          Pattern: "%msg%n"
    RollingFile:
      name: FILE
      fileName: ./s3-mqi.log
      filePattern: "./s3-mqi.log.%d{yyyy-MM-dd-hh-mm}.gz"
      PatternLayout:
        Pattern: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} | %-5level | %logger{1.} [%thread]: %msg %n"
      Policies:
        SizeBasedTriggeringPolicy:
          size: 10 MB
      DefaultRollOverStrategy:
        max: 30
  Loggers:
    logger:
      - name: esa.s1pdgs.cpoc.report.Reporting
        level: DEBUG
        additivity: false
        AppenderRef:
          - ref: REPORT
      - name: esa.s1pdgs.cpoc
        level: info
        additivity: false
        AppenderRef:
          - ref: STDOUT
          - ref: FILE
      - name: com.github.grantneale
        level: info
        additivity: false
        AppenderRef:
          - ref: STDOUT
          - ref: FILE
      - name: org.springframework
        level: error
        additivity: false
        AppenderRef:
          - ref: STDOUT
          - ref: FILE
      - name: kafka
        level: warn
        additivity: false
        AppenderRef:
          - ref: STDOUT
          - ref: FILE
      - name: org.apache
        level: warn
        additivity: false
        AppenderRef:
          - ref: STDOUT
          - ref: FILE
    Root:
      level: error
      AppenderRef:
        ref: STDOUT