# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# TODO: currently there is no docker image available containing the real ipf
ipfImage:
  name: rs-core-ipf-execution-worker

ipfSimImage:
  name: rs-core-s3-ipf-simulator

service:
  port: 8080
  
mqiService:
  port: 8081

s1pro_s3_l0_ipf_execution_worker:
  javaOpts: {}
#   xms: "256m"
#   xmx: "256m"
  uploadCache:
    location: "/opt/s3/uploadCache"
    medium: "Memory"
    size: "16Gi"