name: Build RS Addons

on:
  push:
    branches:
      - '!main'
      - 'release/**'
      - 'develop**'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
      
env:
  RS_CORE_FOLDER: . 
  ARTIFACTORY_BASE: artifactory.coprs.esa-copernicus.eu
  ARTIFACTORY_PROJECT_COMMON: rs-zip-private
  ARTIFACTORY_CORE_PROJECT: rs-addons/s3 
  
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [s3-pug, s3-l0p, s3-acq, s3-ol1, s3-ol2, s3-sl1, s3-sl2, s3-sl2-frp, s3-sr1, s3-mw1, s3-ol1-ntc, s3-sm2-hy, s3-sm2-li, s3-sm2-si, s3-sy2-ntc]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build-core-components
      with:
        WERUM_ARTIFACTORY_USER: ${{ secrets.WERUM_ARTIFACTORY_USER }}
        WERUM_ARTIFACTORY_PASSWORD: ${{ secrets.WERUM_ARTIFACTORY_PASSWORD }}