name: Sentinel 3 Add-on CI

on: 
  push:
    paths:
      - './**'
      - '.github/workflows/build-rs-add-on.yml'
    branches:
      - '!main'
      - 'release/**'
      - 'develop**'
    workflow_dispatch:
    
env:
  ARTIFACTORY_BASE: artifactory.coprs.esa-copernicus.eu
  ARTIFACTORY_PROJECT: rs-docker-private/rs-addon
  ARTIFACTORY_SUB_PROJECT: S3
  

jobs:

   release:
    strategy:
      fail-fast: false
      matrix:
        component: [] #todo
    runs-on: ubuntu-latest
    steps:
   
    - name: Extract branch or tag name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF} | rev | cut -d / -f 1 | rev)"
      id: extract_branch
      
    - name: Generate file name
      shell: bash
      run: |
        addoncomp=${{ matrix.component }}
        addonfilename="RS_ADDON_${addoncomp^^}_${{ steps.extract_branch.outputs.branch }}_$(date '+%Y-%m-%d')"
        echo "##[set-output name=filename;]$(echo ${addonfilename})"
      id: gen_filename
      
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Build structure
      shell: bash
      run: |
        mkdir -p ${{ steps.gen_filename.outputs.filename }}/${{ steps.gen_filename.outputs.filename }}_Executables
        cp -r ${{ matrix.component }}/content/* ${{ steps.gen_filename.outputs.filename }}/${{ steps.gen_filename.outputs.filename }}_Executables
        
    - name: Create PDF
      uses: docker://ghcr.io/coprs/reference-system-software:dependencies_pandoc_latex
      with:
        args: -s --resource-path="/github/workspace/${{ matrix.component }}/" --listings -H /root/.pandoc/listings-setup.tex --table-of-contents --pdf-engine=xelatex --output="${{ steps.gen_filename.outputs.filename }}/${{ steps.gen_filename.outputs.filename }}_Release_Note.pdf" --from=markdown "./${{ matrix.component }}/doc/SRN.md"
    
    - name: Install zip
      uses: montudor/action-zip@v1
    
    - name: Zip
      shell: bash
      run: |
        cd ${{ steps.gen_filename.outputs.filename }}
        zip -qq -r ../${{ steps.gen_filename.outputs.filename }}.zip *
        
    - name: Push to Artifactory
      shell: bash
      run: |
        ls -l
        find ${{ steps.gen_filename.outputs.filename }}
        unzip -l ${{ steps.gen_filename.outputs.filename }}.zip
#      run: curl -u${{ secrets.WERUM_ARTIFACTORY_USER }}:${{ secrets.WERUM_ARTIFACTORY_PASSWORD }} -T ${{ steps.gen_filename.outputs.filename }}.zip "https://${{ env.ARTIFACTORY_BASE }}/artifactory/${{ env.ARTIFACTORY_PROJECT }}/${{ env.ARTIFACTORY_SUB_PROJECT }}/"   